spring:
  application:
    name: pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  profiles:
    active: prod

# mapper.xml 位置
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO

# custom config
com:
  tangl:
    pan:
      bloom:
        filter:
          local:
            items:
              - name: SHARE_SIMPLE_DETAIL
                funnel-type-name: LONG
                expected-insertions: 10000000
                fpp: 0.01

# swagger2
swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.geek.pan
  title: pan-server docs
  description: pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: tangl
  contact-url: geek
  contact-email: geek@163.com
  version: 1.0.0
