spring:
  # redis
  redis:
    database: 0
    host: 14.103.231.136
    password: Qaqa123+
  # 数据库连接
  datasource:
    username: root
    password: Qaqa123+
    url: jdbc:mysql://14.103.231.136:3306/geek_pan?characterEncoding=utf8&serverTimeZone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 14.103.231.136:9876
      bindings:
        testInput:
          destination: testTopic
          group: testGroup
        testOutput:
          destination: testTopic

        errorLogInput:
          destination: errorLogTopic
          group: errorLogGroup
        errorLogOutput:
          destination: errorLogTopic

        fileDeleteInput:
          destination: fileDeleteTopic
          group: fileDeleteGroup
        fileDeleteOutput:
          destination: fileDeleteTopic

        fileRestoreInput:
          destination: fileRestoreTopic
          group: fileRestoreGroup
        fileRestoreOutput:
          destination: fileRestoreTopic

        physicalFileDeleteInput:
          destination: physicalFileDeleteTopic
          group: physicalFileDeleteGroup
        physicalFileDeleteOutput:
          destination: physicalFileDeleteTopic

        userSearchInput:
          destination: userSearchTopic
          group: userSearchGroup
        userSearchOutput:
          destination: userSearchTopic

# oss
com:
  tangl:
    pan:
      server:
        chunk-file-expiration-days: 1
        share-prefix: http://127.0.0.1:5173/share/
