spring:
  application:
    name: pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  profiles:
    active: local

# mapper.xml 位置
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

# swagger2
swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.tangl.pan
  title: pan-server docs
  description: pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: tangl
  contact-url: coco
  contact-email: coco@163.com
  version: 1.0

# oss
com:
  tangl:
    pan:
      storage:
        engine:
      #          fdfs:
      #            connect-timeout: 600
      #            tracker-list:
      #              - 43.139.66.230:22122
      #            group: group1
      #          oss:
      #            bucket-name: pan-test
      #            endpoint: oss-cn-chengdu.aliyuncs.com
      #            access-key-id: LTAI5tCn7uTuaijAzRGoDLMC
      #            access-key-secret: OxWe6Y8hv6j2uNLAugL7EC9K3UlHGm
      #            auto-create-bucket: true
      bloom:
        filter:
          local:
            items:
              - name: SHARE_SIMPLE_DETAIL
                funnel-type-name: LONG
                expected-insertions: 10000000
                fpp: 0.01

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO