spring:
  application:
    name: pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

# swagger2
swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.tangl.pan
  title: pan-server docs
  description: pan-server docs
  terms-of-service-url: https://coco.yn.cn:${server.port}
  contact-name: tangl
  contact-url: tang
  contact-email: tangl@163.com
  version: 1.0.0

logging:
  file: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO